### ISSUE TITLE
Error when decoding

### ISSUE THREAD

**Issue by xiang-xiang-zhu** [Shark-NLP/DiffuSeq#31]
I train the dialogue task, when i want to decoding, error occurs:
```
Traceback (most recent call last):
  File "sample_seq2seq.py", line 210, in <module>
    main()
  File "sample_seq2seq.py", line 184, in main
    return torch._C._nn.linear(input, weight, bias)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:3! (when checking arugment for argument mat2 in method wrapper_mm)
```

**Comment by summmeer** [comment]
Maybe you can try to decode using single GPU.
