### ISSUE TITLE
Problem of Decoding

### ISSUE THREAD

**Issue by medicine-wave** [Shark-NLP/DiffuSeq#8]
I tried to run decode.sh on my own dataset, but it turns the bug. What should I do to solve it ? 
(Ps: I used -nproc_per_node=3 when training, and I tried to change it to 1 or 3 when decoding, but not work)
```
RAM used: 2240.02 MB
RAM used: 2240.02 MB
### End of reading iteration...
  0%|                                                                                                   | 0/101 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "sample_seq2seq.py", line 210, in <module>
    main()
  File "sample_seq2seq.py", line 148, in main
    samples = sample_fn(
  File "/home/DiffuSeq/diffuseq/gaussian_diffusion.py", line 448, in p_sample_loop
    for sample in self.p_sample_loop_progressive(
  File "/home/DiffuSeq/diffuseq/gaussian_diffusion.py", line 517, in p_sample_loop_progressive
    out = self.p_sample(
  File "/home/DiffuSeq/diffuseq/gaussian_diffusion.py", line 373, in p_sample
    out = self.p_mean_variance(
  File "/home/DiffuSeq/diffuseq/gaussian_diffusion.py", line 931, in p_mean_variance
    return super().p_mean_variance(self._wrap_model(model), *args, **kwargs)
  File "/home/DiffuSeq/diffuseq/gaussian_diffusion.py", line 311, in p_mean_variance
    assert t.shape == (B,)
AssertionError
### End of reading iteration...
  0%|                                                                                                   | 0/101 [00:00<?, ?it/s]### End of reading iteration...
  0%|                                                                                                   | 0/101 [00:06<?, ?it/s]
Traceback (most recent call last):
  File "sample_seq2seq.py", line 210, in <module>
    main()
  File "sample_seq2seq.py", line 148, in main
    samples = sample_fn(
  File "/home/DiffuSeq/diffuseq/gaussian_diffusion.py", line 448, in p_sample_loop
    for sample in self.p_sample_loop_progressive(
  File "/home/DiffuSeq/diffuseq/gaussian_diffusion.py", line 517, in p_sample_loop_progressive
    out = self.p_sample(
  File "/home/DiffuSeq/diffuseq/gaussian_diffusion.py", line 373, in p_sample
    out = self.p_mean_variance(
  File "/home/DiffuSeq/diffuseq/gaussian_diffusion.py", line 931, in p_mean_variance
    return super().p_mean_variance(self._wrap_model(model), *args, **kwargs)
  File "/home/DiffuSeq/diffuseq/gaussian_diffusion.py", line 311, in p_mean_variance
    assert t.shape == (B,)
AssertionError
  0%|                                                                                                   | 0/101 [00:06<?, ?it/s]
Traceback (most recent call last):
  File "sample_seq2seq.py", line 210, in <module>
    main()
  File "sample_seq2seq.py", line 148, in main
    samples = sample_fn(
  File "/home/DiffuSeq/diffuseq/gaussian_diffusion.py", line 448, in p_sample_loop
    for sample in self.p_sample_loop_progressive(
  File "/home/DiffuSeq/diffuseq/gaussian_diffusion.py", line 517, in p_sample_loop_progressive
    out = self.p_sample(
  File "/home/DiffuSeq/diffuseq/gaussian_diffusion.py", line 373, in p_sample
    out = self.p_mean_variance(
  File "/home/DiffuSeq/diffuseq/gaussian_diffusion.py", line 931, in p_mean_variance
    return super().p_mean_variance(self._wrap_model(model), *args, **kwargs)
  File "/home/DiffuSeq/diffuseq/gaussian_diffusion.py", line 311, in p_mean_variance
    assert t.shape == (B,)
AssertionError
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 87758 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 87759 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 87757) of binary: /home/anaconda3/envs/kaggle_env/bin/python
Traceback (most recent call last):
  File "/home/anaconda3/envs/kaggle_env/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/anaconda3/envs/kaggle_env/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/anaconda3/envs/kaggle_env/lib/python3.8/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/home/anaconda3/envs/kaggle_env/lib/python3.8/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/home/anaconda3/envs/kaggle_env/lib/python3.8/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/home/anaconda3/envs/kaggle_env/lib/python3.8/site-packages/torch/distributed/run.py", line 752, in run
    elastic_launch(
  File "/home/anaconda3/envs/kaggle_env/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/anaconda3/envs/kaggle_env/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 245, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
sample_seq2seq.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2022-11-26_07:57:08
  host      : gpu-server2
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 87757)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
############################## decoding finished...
```

**Comment by xiaomanai** [comment]
Please try to modify batch size

**Comment by summmeer** [comment]
This bug is fixed:
https://github.com/Shark-NLP/DiffuSeq/blob/bfd0ffd0a914c2afd5720f7bc36cfd1d0d8995ce/sample_seq2seq.py#L146
